### ISSUE TITLE
Refactoring the task as like Sampler

### ISSUE THREAD

**Issue by NicolasBn** [dsccommunity/DscResource.Test#110]
Refactoring the tasks as like Sampler to avoid the repetitive lines of code.

See : 
https://github.com/gaelcolas/Sampler/blob/main/Sampler/scripts/Set-SamplerTaskVariable.ps1

https://github.com/gaelcolas/Sampler/blob/main/.build/tasks/Invoke-Pester.pester.build.ps1#L58

**Comment by johlju** [comment]
Yep we should try to use the public alias that Sampler is exporting so we use the same code (functionality) as Sampler does. To avoid re-invent the wheel in each module that adds "Sampler" tasks. 🤔

**Comment by NicolasBn** [comment]
I have been starting to work on 're-invent the wheel' :).

Before that, I wondered if it was a good choice to create a dependance DSCResource.Test to Sampler.

**Comment by johlju** [comment]
Maybe not. The tasks are meant to run with Sampler but the tests are not, so maybe we should re-invent the wheel here. So continue your work.

**Comment by NicolasBn** [comment]
I checked my code and I changed my think.
There's already a dependency between DSCResource.Test and Sampler. 
The tasks of DSCResrouce.Test use Sampler cmdlet like `Get-SamplerBuiltModuleBase`.

Now, I think one more dependency isn't a big deal.

I'll try to see wath the change involved.

**Comment by johlju** [comment]
No, agree. Let’s try to use the alias that points to the script in Sampler. 😊

**Comment by NicolasBn** [comment]
I tested it on FileSytemDSC.
- Before : 

![image](https://user-images.githubusercontent.com/25097989/120113410-a8608200-c17a-11eb-9b3f-5020858bde05.png)


- After : 

![image](https://user-images.githubusercontent.com/25097989/120113390-9848a280-c17a-11eb-9927-ad775de0b460.png)

No issue. But I will parse the code to see if all the varaibles were initiate.

**Comment by johlju** [comment]
Looks like it outputted all variables from the script in Sampler. That is the first section of the output in the second image. Also the ProjectName is outputted a second time so that should be removed as well from the task. :)

**Comment by NicolasBn** [comment]
Solved in https://github.com/dsccommunity/DscResource.Test/pull/111
