### ISSUE TITLE
`using module` for class-based DSC resource tests?

### ISSUE THREAD

**Issue by bozho** [dsccommunity/DscResource.Test#114]
I'm quite new with Pester and am giving it a go with testing our class-based DSC resources. I'm using Pester 5.3.0.

It looks like Pester does not/cannot mock PS functions executed from PowerShell class methods unless the class module is imported with `using module` statement.

So, assume we have a trivial class-based resource `Foo` and its `Get()` method executes `Get-ChildItem`. Copying some other community resources' tests, we'd go with something like this:

```
$script:dscModuleName = 'MyModule'
$script:dscResourceName = 'Foo'

function Invoke-TestSetup {
    Import-Module -Name DscResource.Test -Force -ErrorAction 'Stop'

    $script:testEnvironment = Initialize-TestEnvironment `
        -DSCModuleName $script:dscModuleName `
        -DSCResourceName $script:dscResourceName `
        -ResourceType 'Class' `
        -TestType 'Unit'
}

function Invoke-TestCleanup {
    Restore-TestEnvironment -TestEnvironment $script:testEnvironment
}

Invoke-TestSetup

InModuleScope "Foo" {
    Describe "Description" {
        Context "My Context" {
            BeforeAll {
                Mock -CommandName Get-ChildItem -MockWith {
                    throw "BAR!"
                }
                $foo = [Foo]::new()
            }

            It "The Test" {
                { $foo.Get() } | Should -Throw
            }
        }
    }
}
```

The above test will fail, as `Get()` method does not seem to execute the mocked `Get-ChildItem`.

Now, if we replace the test setup with an appropriate `using module` statement:
```
$script:dscModuleName = 'MyModule'
$script:dscResourceName = 'Foo'

$scriptBody = "using module <path to module source>\$script:dscResourceName\$script:dscResourceName.psm1"
$script = [ScriptBlock]::Create($scriptBody)
. $script

InModuleScope "Foo" {
    Describe "Description" {
        Context "My Context" {
            BeforeAll {
                Mock -CommandName Get-ChildItem -MockWith {
                    throw "BAR!"
                }
                $foo = [Foo]::new()
            }

            It "The Test" {
                { $foo.Get() } | Should -Throw
            }
        }
    }
}
```

The above test will pass, as `Get()` will call into the mocked function, which throws. The behaviour is the same for "regular" classes (not decorated with DSC resource attributes).

Lots of questions here :)
* Am I missing something/doing something wrong?
* Should this be considered a `DscResource.Test` bug? 
* Should I even be using `DscResource.Test` for this kind of testing?

Thank you!

**Comment by johlju** [comment]
We don't use DscResource.Test for such testing, it wrongly assumes the class-based resource is standalone like a MOF-based resource which they shouldn't be, but instead part of the main module.

Please look at DnsServerDsc and use that as a base line for having both class-based and MOF-based resources. Make sure to use the same scaffolding and build configuration. You see how it is tested here https://github.com/dsccommunity/DnsServerDsc/blob/main/tests/Unit/Classes/DnsRecordA.tests.ps1.

**Comment by bozho** [comment]
Thank you, I'll have a look!

**Comment by bozho** [comment]
@johlju Sorry to reopen, just wanted to check if I understand what you do in `DnsServerDsc`: your build process dumps all class' sources to `DnsServerDsc.psm1` file, which is imported using `Import-Module`, and then you can use a simple `using module DnsServerDsc` in your tests, right?

We keep our class-based DSC resources in separate submodules and use `NestedModules` in the main manifest file. This approach makes the build essentially trivial, keeps modules nicely separated, but would make us use that ugly dynamic PowerShell to execute `using module` with a correct path for each submodule tested.

**Comment by johlju** [comment]
We are not using `using module` at all. But that might be possible if you like that. The module is just imported using `Import-Module` in the tests. 

The classes are separate in the source folder. The build pipeline concatenate everything in the correct order (classes dependent on each other) inside the built module script file (one si for file). The module script file is then reference as the RootModule in the module manifest. 

The tests import the built module. Testing is done against the same file (the built module) that will be published (if tests passes). 

The pipeline will translate back code coverage hits and missed from the test run to the correct source file.

**Comment by johlju** [comment]
Btw. the pipeline comes from the Sampler (https://GitHub.com/gaelcolas/Sampler) project that makes it easy to set up an new project with its built-in Plaster template `dsccommunity`. Though for classes some changes might be needed (which can be copied of DnsServerDsc)

**Comment by bozho** [comment]
Ah, right... `using module` is present `DnsRecordBase.tests.ps1` and `ResourceBase.Tests.ps1`...

I've had a look at `Sampler`, it looks a bit overkill for my needs, but I'll give it a go when I find some time :-)

The reason I went digging around is the original question: the trivial class example where PS functions called by class methods do not seem to be mocked in Pester v5 unless the class module is imported with `using module`. I see you use Pester v4 in `DnsServerDsc`, I'll try this example in v4.

BTW, is there a better place to discuss this issue?

**Comment by bozho** [comment]
Ah... Please ignore this.

With Pester v5, `Import-Module` needs to be executed inside `BeforeDiscovery` block. Mocking PS functions works as expected then...

**Comment by johlju** [comment]
I did not know that `using module` existed there. :) Looking at the test pipeline the first test to be executed is DnsRecordA, and that one does not have `using module` so it might be possible to remove it from the other places. 

This was as a perfect place as another to discuss this, though you will get faster response from the #dsc Slack/Discord channel 😊 See the https://dsccommunity.org how to connect with the community.

**Comment by johlju** [comment]
It seems `using module` is necessary to be able to inheriting a parent class in the tests. That is why it is not needed in the other tests. 🙂 I should have known that, because I wrote one of the tests 😉
