### ISSUE TITLE
`Get-InvalidResultRecord`: Should not have alias `Get-ObjectNotFoundRecord`

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.Test#126]
The command `Get-InvalidResultRecord` should not have the alias `Get-ObjectNotFoundRecord`.

https://github.com/dsccommunity/DscResource.Test/blob/73d6c3290572a0b065084a1adcaa1eb5a8da5994/source/Public/Get-InvalidResultRecord.ps1#L15

 `Get-ObjectNotFoundRecord` should be a public command. The code in `Get-InvalidResultRecord` should be moved to a private function `Get-SystemExceptionRecord` that both the publoic commands (`Get-InvalidResultRecord` and `Get-ObjectNotFoundRecord`) uses.

**Comment by johlju** [comment]
The alias should also be removed from the README.md.

https://github.com/dsccommunity/DscResource.Test/blob/73d6c3290572a0b065084a1adcaa1eb5a8da5994/README.md?plain=1#LL228-L228C21

**Comment by dan-hughes** [comment]
@johlju, I know this is scope creep, but what about adding an extra parameter to `Get-SystemExceptionRecord` to pass the exception type and then `Get-InvalidOperationRecord`, `Get-InvalidResultRecord` and `Get-ObjectNotFoundRecord` can all can use the same private function?

See this [commit](https://github.com/dan-hughes/DscResource.Test/commit/98440cb83bab12eab9605d4b5e5bb6ed4d6b3335).
