### ISSUE TITLE
How to suppress a PSScriptAnalyzer rule?

### ISSUE THREAD

**Issue by raandree** [dsccommunity/DscResource.Test#135]
I want to use this module for checking the code in [DscBuildHelpers](https://github.com/gaelcolas/DscBuildHelpers). Some functions however are much more helpful if they write something to the console. I am trying to suppress the rule 'PSAvoidUsingWriteHost' by following [this recommendation](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules). Now I have this error:

```
[-] Should not suppress the required rule 'PSAvoidUsingWriteHost' 3ms (2ms|0ms)
    Expected collection PSAvoidUsingWriteHost to not contain 'PSAvoidUsingWriteHost', because no module script file should suppress a required Script Analyzer rule, but it was found.        
    at $_ | Should -Not -BeIn $suppressedRuleNames -Because 'no module script file should suppress a required Script Analyzer rule', D:\DscBuildHelpers\output\RequiredModules\DscResource.Test\0.16.3\Tests\QA\PSSAResource.common.v5.Tests.ps1:172
    at <ScriptBlock>, D:\DscBuildHelpers\output\RequiredModules\DscResource.Test\0.16.3\Tests\QA\PSSAResource.common.v5.Tests.ps1:172
```

How can I allow calls to `Write-Host` and still make use of this module?

**Comment by dan-hughes** [comment]
Currently it doesn't look like you can supress a specific rule if it's marked as required.

You could add the following into the `build.yml` as a work around.
```yaml
Pester:
    ExcludeTag:
    - RequiredPSSA
```

**Comment by raandree** [comment]
Thanks, @dan-hughes, that did it.

**Comment by johlju** [comment]
I also pushed a new full release yesterday.

**Comment by dan-hughes** [comment]
@johlju, I'm not sure the fix I made will resolve this as that for Pester 4. It doesn't look like _required_ rules can be suppressed.

**Comment by raandree** [comment]
This issue is bothering us with [Sampler.DscPipeline](https://github.com/SynEdgy/Sampler.DscPipeline). I see an easy option to fix that.
