### ISSUE TITLE
Fails to exclude source files from HQRM tests

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.Test#142]
#### Details of the scenario you tried and the problem that is occurring
When running the HQRM test for a repo using Pester 4 it seems it fails to exclude source files that are excluded in the build configuration.

Se more information in PR https://github.com/dsccommunity/SharePointDsc/pull/1440.

#### Steps to reproduce the problem
In a source file suppress the rule PSAvoidUsingWriteHost, for example in the source file in the relative path `SharePointDsc/Modules/SharePointDsc.Reverse/SharePointDsc.Reverse.psm1`:

```powershell
[CmdletBinding()]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '', Scope = 'Function', Target = '*')]
param ()
```

Then try to exclude the relative path in the build configuration:

```yaml
DscTest:
  ExcludeSourceFile:
    - output
    - 'SharePointDsc/Modules/SharePointDsc.Reverse/SharePointDsc.Reverse.psm1'
```

#### Expected behavior
Should exclude the file and the tests should not fail.

#### Current behavior
Does not exclude the file and the test fails due to suppressing a required rule.

#### Suggested solution to the issue
It should exclude the source files according to the code but it doesn't happen. Haven't debugged so not sure where the issue is.

It should filter out the excluded files here:
https://github.com/dsccommunity/DscResource.Test/blob/14acda0bc0a6a9698bfb8fd41da42adfe08b09f0/source/Tests/QA/PSSAResource.common.v4.Tests.ps1#L82

Using the filter: https://github.com/dsccommunity/DscResource.Test/blob/14acda0bc0a6a9698bfb8fd41da42adfe08b09f0/source/Private/WhereSourceFileNotExcluded.ps1#L1

#### The operating system the target node is running
Windows and also using Pester 4

#### Version and build of PowerShell the target node is running
PowerShell 5.1

#### Version of the module that was used
v0.16.3

**Comment by dan-hughes** [comment]
`$ExcludeSourceFile` is not passed down to/available in the filter. I think the logic on the if statement is broken too, but without the exclusions being seen in the filter it never does anything.

**Comment by johlju** [comment]
Apparently it works, and maybe the reason was the single quotes 🤔  Closing this and it can be reopen if there is more information in the future.
