### ISSUE TITLE
Add E2E Test Type to Initialize-TestEnvironment

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/DscResource.Test#48]
The Resource Module xPSDesiredStateConfiguration has resources that have E2E type tests. These tests contain both unit tests and integration tests.

To support these we need to add a test type E2E that runs both the init code for unit and integration tests.

Until this is resolved xPSDesiredStateConfiguration can not be transferred unless we split the tests out (which I'd rather not do).

**Comment by johlju** [comment]
@PlagueHO Is this still an issue or was it resolved by PR #49?

**Comment by PlagueHO** [comment]
Resolved by #49
