### ISSUE TITLE
Add a test that checks if the schema.mof complies with the schema

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/DscResource.Test#65]
The function Get-MOFSchemaObject in the DscResource.DocGenerator module fails when the class definition in the schema.mof file has two spaces behind the class name:
```
class MSFT_SPPasswordChangeSettings<space><space>: OMI_BaseResource
```

Would be nice if there is a HQRM test that validates if the schema of a resource complies with the DSC MOF schema definition or at least the number of spaces behind the class name.

What would be the best way of validating the mof file?

**Comment by gaelcolas** [comment]
It should do that already using mofcomp via xDscResourceDesigner's test-dscresource.
The problem is that mofcomp requires to run as admin or it'll skip the test.

I'd rather change that to use the dscrresourcecache class, but I don't have time en.

**Comment by ykuijs** [comment]
Just tested if mofcomp detects this issue and unfortunately it doesn't.

**Comment by ykuijs** [comment]
@gaelcolas Been looking into the dscrresourcecache option, but cannot find anything. Can you explain a little more, so I can test that method as well?

**Comment by johlju** [comment]
It is because of this row does not use regex to do the comparison. It is a valid schema, it is just the code that assumes it always look one way :)

https://github.com/dsccommunity/DscResource.DocGenerator/blob/e161d60c70a60b6378aa116364ad1e5083b226e3/source/Private/Get-MofSchemaObject.ps1#L64
