### ISSUE TITLE
HQRM test should be converted to support both Pester 4 and Pester 5

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.Test#75]

**Comment by NicolasBn** [comment]
The last release of pester module doesn't support parametric scripts. 

This feature is added in version [5.0.5-beta1](https://github.com/pester/Pester/releases/tag/5.0.5-beta1)

**Comment by johlju** [comment]
This is documented in Pester docs now https://pester.dev/docs/usage/data-driven-tests#providing-external-data-to-tests

**Comment by johlju** [comment]
I working on this.
