### ISSUE TITLE
Remove Test Manifest has Class based resource in nested modules

### ISSUE THREAD

**Issue by gaelcolas** [dsccommunity/DscResource.Test#85]
The best practice (IMO) is to have the DSC Class based resources merged into the Main module's PSM1, and not under a subfolder, and not adding it to the nested module as a psm1.

Currently the [DscResource.Test](https://github.com/dsccommunity/DscResource.Test/blob/master/source/Tests/QA/ModuleManifest.common.Tests.ps1#L60-L62) forces you to have it under nested module as soon as there is a class based DSC resource, even though it's not necessarily a PSM1.

This check should be removed.

**Comment by johlju** [comment]
The classes based resource was meant to be under DSCClassResources like https://github.com/bgelens/DockerDsc. If that is not the case anymore then there are two patterns that need to be supported. 🤔

**Comment by gaelcolas** [comment]
I'd argue that only one is good and should be encouraged and defined as HQRM.

**Comment by johlju** [comment]
Yes I can agree with that. I'm not sure there is any reason for the classes to be in a DSCClassResources folder in the module, for example for discoverability on different PS version or cmdlets, or if there was just for human radability? 🤔 

Maybe we could have source/DSCClassResources/myClassResource, the module that is generated is just concatenating them into one module file (the pattern you suggest)? Using such folder in source would differentiate them from other classes. It would also be more natural if there were both schema mof and class-based in the same module. 🤔
