### ISSUE TITLE
The test "Should not suppress any required PS Script Analyzer rules" does not work

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.Test#96]
In the test `PSSAResource.common.Tests.ps1` the variable `$requiredPssaRuleNames` should be changed to `$PSSA_rule_config.required_rules` so the test _Should not suppress any required PS Script Analyzer rules_ works.

https://github.com/dsccommunity/DscResource.Test/blob/75778b90f96df95304950711244bbda3076f9350/source/Tests/QA/PSSAResource.common.Tests.ps1#L110

**Comment by dan-hughes** [comment]
Have a fix for this once #126 is merged to add the pipelines fix.

**Comment by raandree** [comment]
@johlju, does it mean that `DscResource.Test` version 0.16.2 does not let you exclude rules? That would explain my trouble.

When are you going to release a full version with the fix? It would come handy for my working on `DscBuildHelpers`.
